### PR TITLE
add a flag for long vowels to shiritori

### PR DESCRIPTION
**Pull request by Riolku**
This flag means that after words like りょこう are played, こ or う words are accepted.

Disclaimers: Shiritori forever is just setup differently. I can't pass a game object around, so for now I pass an empty config appropriately. I'd appreciate help here.

### CODE REVIEW

**Comment by mistval** [comment]
👍 This looks pretty great. It seems to break shiritori forever though, I get an error when I start it with `k!settings shiritoriforever enabled`:

```
TypeError: Cannot read properties of undefined (reading 'length')
    at JapaneseGameStrategy.getViableNextResult ([C:\Users\rschm\code\kotoba\node-common\shiritori\japanese_game_strategy.js:185:33]())
    at sendFirstWord ([c:\Users\rschm\code\kotoba\bot\src\discord\shiritori_forever_helper.js:315:45]())
```

Looks like an easy fix, just have to change the way sendFirstWords calls getViableNextResult to match the new argument type.

Also wanted to double-check some behavior with you. For `むはんどうじゅう`, it accepts `う`, `ゆ`, `じゅ` to start the next word. Is that intentional? (the  `ゆ` one seems a little weird to me but it's fine with me if it's indeed what you want).

For Shiritori Forever, you could add the same setting under the `Shiritori Forever` category with a setting ID like `shiritori_forever/lax_long_vowels`, and then in shiritori_forever_helper.js::tryHandleMessage(), you could do this to get the value of the setting:

```js
const laxLongVowels = await monochrome.getSettings().getInternalSettingValue(
    'shiritori_forever/lax_long_vowels',
    msg.channel.guild.id,
    msg.channel.id,
    '',
  );
```

Let me know if that helps.

**Comment by Riolku** [comment]
Wow that was very helpful! I'll have to implement your changes shortly. As for the behavior with `むはんどうじゅう`, I'm rather indifferent. We could talk about adding another flag for that too I guess, it should be easier once this architecture is setup. Something like `allowSmallLetters`.

**Comment by Riolku** [comment]
Ok, it took some doing, I had to set up a discord bot, but this should do it. I rearranged the calls a bit because I really hated passing `{ config: [] }`.

**Comment by mistval** [comment]
👍 Looks good to me. Merging and will plan to deploy to production at some point today. Thanks!

**Comment by Riolku** [comment]
Do you mind letting me know when you deploy?

**Comment by mistval** [comment]
👍 Just deployed the API and website. A lot of people are using the bot right now (and it's stateful) so I will wait a bit and let you know when the bot is deployed.

**Comment by mistval** [comment]
Everything has now been redeployed (bot, API, website).

**Pull request merged**
